In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import time
import seaborn as sns
import numpy as np
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
import statsmodels.formula.api as sm
import statsmodels.regression.linear_model as lm


#to perform the train test split of the data, the train test split function is imported from sklearn
from sklearn.model_selection import train_test_split
#the given problem is a classificaton problem. Hence linear regression is used for ML algorithm
from sklearn.linear_model import LinearRegression

In [2]:
file = "test_dataset.csv"
tds1 = pd.read_csv(file)
tds1 = tds1[['Artist', 'Track','popularity','acousticness', 'danceability', 'duration_ms', 'energy',
       'instrumentalness', 'key', 'liveness', 'loudness', 'mode',
       'speechiness', 'tempo', 'time_signature', 'valence']]
tds1.head()

,Artist,Track,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,casual,I Didn't Mean To,21,0.063,0.751,218933,0.549,0.000025,6,0.1060,-10.508,0,0.4290,92.224,4,0.553
1,Casual,I Didn't Mean To,21,0.063,0.751,218933,0.549,0.000025,6,0.1060,-10.508,0,0.4290,92.224,4,0.553
2,The Box Tops,Soul Deep,37,0.195,0.749,147760,0.530,0.000035,9,0.0748,-12.940,1,0.0326,121.395,4,0.966
3,Sonora Santanera,Amor De Cabaret,50,0.689,0.699,183027,0.519,0.000471,8,0.9350,-6.422,1,0.0290,102.463,4,0.676
4,Adam Ant,Something Girls,19,0.218,0.606,232107,0.937,0.005870,0,0.1630,-3.808,1,0.0443,120.135,4,0.853

# Linear Regression

## Define Datasets

In [4]:
#Combined Dataset
dfcombine = tds1
#dfcombine = dfcombine.reset_index(inplace=True, drop=True)

#Target Dataset
dfy = pd.DataFrame(tds1["popularity"])

#all the independant variables/predictors are named as dfx
dfx = dfcombine.drop(columns=['Artist', 'Track','popularity'])
dfx.head()

,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,0.063,0.751,218933,0.549,0.000025,6,0.1060,-10.508,0,0.4290,92.224,4,0.553
1,0.063,0.751,218933,0.549,0.000025,6,0.1060,-10.508,0,0.4290,92.224,4,0.553
2,0.195,0.749,147760,0.530,0.000035,9,0.0748,-12.940,1,0.0326,121.395,4,0.966
3,0.689,0.699,183027,0.519,0.000471,8,0.9350,-6.422,1,0.0290,102.463,4,0.676
4,0.218,0.606,232107,0.937,0.005870,0,0.1630,-3.808,1,0.0443,120.135,4,0.853

In [5]:
dfy.head()

   popularity
0          21
1          21
2          37
3          50
4          19

## Train Set  - Linear Regression

In [6]:
dfx.reset_index(inplace=True, drop=True)
dfy.reset_index(inplace=True, drop=True)
dfy.head()

   popularity
0          21
1          21
2          37
3          50
4          19

In [ ]:
#Copy the code from Brooklyn 4.0 to set up the model as far as possible....